apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: klopapier.frank.elsinga.de
    namespace: klopapier
spec:
    commonName: klopapier.frank.elsinga.de
    dnsNames:
        - klopapier.frank.elsinga.de
    secretName: klopapier.frank.elsinga.de
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
