apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: template_project-ingress-http
    labels:
        app: template_project
    namespace: template_project
spec:
    entryPoints:
        - web
    routes:
        - kind: Rule
          match: Host(`template_url.frank.elsinga.de`)
          services:
              - name: noop@internal
                kind: TraefikService
          middlewares:
              - name: https
