apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: template_project-ingress
    labels:
        app: template_project
    namespace: template_project
spec:
    entryPoints:
        - websecure
    routes:
        - kind: Rule
          match: Host(`template_url.frank.elsinga.de`) && PathPrefix(`/media/`)
          priority: 11
          services:
              - name: template_project-svc
                port: 7000
        - kind: Rule
          match: Host(`template_url.frank.elsinga.de`)
          priority: 10
          services:
              - name: template_project-svc
                port: 8000
    tls:
        secretName: template_url.frank.elsinga.de
