apiVersion: v1
kind: PersistentVolume
metadata:
    name: klopapier-pv
    namespace: klopapier
    labels:
        app: klopapier
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 100Mi
    persistentVolumeReclaimPolicy: Delete
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/data/klopapier'
