apiVersion: v1
kind: PersistentVolume
metadata:
    name: template_project-pv
    namespace: template_project
    labels:
        app: template_project
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 100Mi
    persistentVolumeReclaimPolicy: Delete
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: '/mnt/data/template_project'
