apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: template_project-mediafiles-pvc
    namespace: template_project
    labels:
        app: template_project
        type: local
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 50Mi
