apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: klopapier-mediafiles-pvc
    namespace: klopapier
    labels:
        app: klopapier
        type: local
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 50Mi
